services:
  front:
    image: node:22-alpine
    ports:
      - 5173:5173
    volumes:
      - ./front:/app
    working_dir: /app
    command: sh -c "npm i && npm run dev"


  back:
    image: directus/directus
    ports:
      - 8055:8055
    # j'ajoute des variables d'environnement
    # → https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-environment-attribute
    environment:
      # configure les accès à la BDD
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: mydb
      DB_USER: user
      DB_PASSWORD: password
      # initialise l'admin
      ADMIN_EMAIL: admin@oclock.io
      ADMIN_PASSWORD: oclock
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
