

services:
  serveur-web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./front:/usr/share/nginx/html

  back:
    image: node:22-alpine
    ports:
      - 3000:3000
    volumes:
      - ./back:/app
    working_dir: /app
    # je dois dire au conteneur d'installer les dépendances
    # et de lancer le serveur
    # command: sh -c "npm install && npm start"
    command: sh -c "npm install && node index.js"



  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  vite:
    image: your-vite-image
    ports:
      - "5173:5173"

  directus:
    image: directus/directus
    ports:
      - "8055:8055"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  docusaurus:
    image: your-docusaurus-image
    ports:
      - "3000:3000"

volumes:
  postgres-data:
